apiVersion: v2
name: o11y

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: grafana
    version: 8.8.4
    repository: "file://./charts/grafana"
  - name: prometheus
    version: 27.1.0
    repository: "file://./charts/prometheus"