apiVersion: v1
appVersion: 1.8.1
description: Serverless for Real-Time and Data-Driven Applications
home: https://nuclio.io
icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
maintainers:
- email: erand@iguazio.com
  name: Eran Duchan
- email: odedm@iguazio.com
  name: Oded Messer
- email: liranb@iguazio.com
  name: Liran Ben Gida
name: nuclio
sources:
- https://github.com/nuclio/nuclio
version: 0.12.1
