apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://github.com/ray-project/ray/raw/master/doc/source/images/ray_header_logo.png
name: ray-cluster
version: 1.2.1

dependencies:
- name: kuberay-operator
  repository: file://./charts/kuberay-operator
  version: 1.2.1
- name: redis
  repository: file://./charts/redis
  version: 19.1.0
