{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "o11y-agent.appname" . }}-{{ .Release.Name }}
  labels:
    {{- include "o11y-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "o11y-agent.appname" . }}-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "o11y-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
